// Run with Vite on port 5173. Set PLAYWRIGHT_MODULE if Playwright is installed outside this repo.
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
import { mkdir } from 'node:fs/promises';
await mkdir('output', { recursive: true });
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true});
const errors=[];
const run=async(viewport,label)=>{
  const context=await browser.newContext({viewport,deviceScaleFactor:1});
  const page=await context.newPage();
  page.on('pageerror',e=>errors.push(`${label}: ${e.message}`));
  await page.clock.install();
  await page.goto('http://localhost:5173/');
  await page.screenshot({path:`output/${label}-home.png`,fullPage:true});
  await page.locator('[data-action="new"]').click();
  await page.locator('[data-action="choose-yi"]').click();
  await page.locator('#plague-name').fill('长夜');
  await page.locator('#name-form button[type="submit"]').click();
  for(let i=0;i<9;i++)await page.locator('[data-action="prologue-next"]').click();
  await page.locator('[data-action="first-disease"][data-id="cold_plague"]').click();
  let state=JSON.parse(await page.evaluate(()=>window.render_game_to_text()));
  assert.equal(state.mapMode,'realm');
  assert.equal(await page.locator('[data-macro]').count(),6);
  assert.equal(await page.locator('[data-region]').count(),0);
  if(label==='mobile')for(const box of await page.locator('[data-macro]').evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect().toJSON())))assert.ok(box.width>=44&&box.height>=44,'macro region touch target');
  await page.screenshot({path:`output/${label}-realm.png`,fullPage:true});
  await page.locator('[data-macro="hedong"]').click();
  assert.equal(await page.locator('.macro-detail h2').textContent(),'河东郡');
  await page.screenshot({path:`output/${label}-realm-selection.png`,fullPage:true});
  await page.locator('[data-action="enter-macro"]').click();
  state=JSON.parse(await page.evaluate(()=>window.render_game_to_text()));
  assert.equal(state.mapMode,'region');
  assert.equal(state.activeMacroRegion,'hedong');
  assert.deepEqual(state.visibleRegions.sort(),['he_dong','qiu_yuan','shan_bei','yun_zhou'].sort());
  assert.equal(await page.locator('[data-region]').count(),4);
  if(label==='mobile'){const box=await page.locator('[data-region="he_dong"] .hit').boundingBox();assert.ok(box.width>=44&&box.height>=44,'node touch target');}
  await page.locator('[data-region="he_dong"]').click();
  await page.screenshot({path:`output/${label}-placement.png`,fullPage:true});
  if(label==='mobile'){
    const leaf=await page.locator('.detail-panel').boundingBox();
    assert.ok(leaf.x>=12&&leaf.x+leaf.width<=viewport.width-12,'archive leaf keeps side margins');
    assert.equal(await page.locator('.detail-panel').evaluate(el=>getComputedStyle(el).borderTopLeftRadius),'1px');
    assert.ok(await page.locator('.dossier-date').isVisible());
    assert.ok(await page.locator('.dossier-close-label').isVisible());
    await page.locator('.detail-close').click();
    assert.equal(await page.locator('.detail-panel').count(),0);
    await page.locator('[data-region="he_dong"]').click();
  }
  await page.locator('details[data-disclosure]').first().locator('summary').click();
  await page.locator('[data-action="drop"]').click();
  assert.equal(await page.locator('details[data-disclosure]').first().getAttribute('open'),'','disclosure survives render');
  await page.locator('[data-action="close-modal"]').click();
  if(label==='mobile')await page.locator('.detail-close').click();
  await page.locator('[data-action="speed"][data-value="0"]:visible').first().click({force:true});
  state=JSON.parse(await page.evaluate(()=>window.render_game_to_text()));
  assert.equal(state.drops,1);assert.equal(state.outbreaks.length,1);
  await page.screenshot({path:`output/${label}-game.png`,fullPage:true});
  for(let i=0;i<10;i++)await page.evaluate(()=>window.advanceTime());
  assert.equal(await page.locator('.turn-brief').count(),1);
  await page.screenshot({path:`output/${label}-report.png`,fullPage:true});
  state=JSON.parse(await page.evaluate(()=>window.render_game_to_text()));
  assert.equal(state.turn,1);assert.ok(state.power>=1);
  await page.screenshot({path:`output/${label}-map.png`,fullPage:true});
  await page.locator('[data-region="he_dong"]').click();
  await page.locator('[data-action="stance"][data-value="spread"]').click();
  if(label==='mobile'){
    await page.locator('.detail-scroll').evaluate(el=>el.scrollTop=0);
    await page.screenshot({path:'output/mobile-dossier-infected.png',fullPage:true});
    await page.locator('details[data-disclosure^="events-"] summary').click();
    await page.locator('.detail-scroll').evaluate(el=>el.scrollTop=el.scrollHeight);
    await page.screenshot({path:'output/mobile-dossier-events.png',fullPage:true});
    await page.locator('.detail-handle').click();
    assert.equal(await page.locator('.detail-panel').count(),0,'page-edge close retained');
    await page.locator('[data-region="he_dong"]').click();
  }
  state=JSON.parse(await page.evaluate(()=>window.render_game_to_text()));
  assert.equal(state.outbreaks.find(o=>o.region==='he_dong').stance,'spread');
  if(label==='mobile') await page.locator('.detail-close').click();
  const beforeBox=await page.locator('.world-svg').getAttribute('viewBox');
  await page.locator('[data-action="zoom-in"]').click();
  assert.notEqual(await page.locator('.world-svg').getAttribute('viewBox'),beforeBox);
  await page.locator('[data-action="zoom-reset"]').click();
  assert.equal(await page.locator('.world-svg').getAttribute('viewBox'),beforeBox);
  if(label==='mobile') {
    const stage=await page.locator('#map-stage').boundingBox();
    await page.mouse.move(stage.x+8,stage.y+stage.height*.4);await page.mouse.down();await page.mouse.move(stage.x+90,stage.y+stage.height*.4,{steps:4});await page.mouse.up();
    assert.notEqual(await page.locator('.world-svg').getAttribute('viewBox'),beforeBox,'map should pan on touch-sized screen');
  }
  const turnBeforeReturn=state.turn;
  await page.locator('[data-action="return-realm"]').click();
  state=JSON.parse(await page.evaluate(()=>window.render_game_to_text()));
  assert.equal(state.mapMode,'realm');
  assert.equal(state.activeMacroRegion,null);
  assert.equal(state.turn,turnBeforeReturn,'returning to realm must not advance time');
  assert.equal(state.selectedDisease,'cold_plague','returning to realm must retain selected disease');
  assert.equal(state.outbreaks.find(o=>o.region==='he_dong').disease,'cold_plague');
  await page.screenshot({path:`output/${label}-realm-infected.png`,fullPage:true});
  await page.locator('[data-tab="news"]:visible').first().click();
  await page.locator('[data-action="toggle-log"]').first().click();
  assert.ok(await page.locator('.impact').count());
  await page.locator('[data-tab="codex"]:visible').first().click();
  assert.equal(await page.locator('.evolution-card').count(),8);
  assert.equal(await page.locator('.turn-brief').count(),0);
  for(let i=0;i<8;i++){await page.locator('[data-action="select-disease"]').nth(i).click();assert.equal(await page.locator('.evolution-card:visible').count(),1);assert.equal(await page.locator('[data-action="select-disease"]').nth(i).getAttribute('aria-pressed'),'true');}
  await page.locator('[data-action="select-disease"]').first().click();
  await page.screenshot({path:`output/${label}-codex.png`,fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'codex overflow');
  await page.locator('[data-tab="court"]:visible').first().click();
  assert.equal(await page.locator('.faction-card').count(),6);
  for(let i=0;i<6;i++){await page.locator('[data-action="select-faction"]').nth(i).click();assert.equal(await page.locator('.faction-card:visible').count(),1);}
  await page.screenshot({path:`output/${label}-court.png`,fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'court overflow');
  await page.locator('[data-tab="news"]:visible').first().click();
  await page.screenshot({path:`output/${label}-news.png`,fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'news overflow');
  await page.keyboard.press('Escape');
  await page.locator('[data-action="speed"][data-value="1"]:visible').click();
  await page.locator('[data-tab="codex"]:visible').first().click();
  const readDay=JSON.parse(await page.evaluate(()=>window.render_game_to_text())).dayInTurn;
  await page.clock.runFor(4000);
  assert.equal(JSON.parse(await page.evaluate(()=>window.render_game_to_text())).dayInTurn,readDay,'reading pauses time');
  assert.ok(await page.locator('.reading-note').isVisible());
  await page.keyboard.press('Escape');
  await page.clock.runFor(3100);
  assert.notEqual(JSON.parse(await page.evaluate(()=>window.render_game_to_text())).dayInTurn,readDay,'return resumes time');
  await page.locator('[data-action="speed"][data-value="0"]:visible').click();
  await page.keyboard.press('Escape');
  assert.ok(await page.locator('[role="dialog"]').isVisible());
  await page.keyboard.press('Shift+Tab');
  assert.equal(await page.evaluate(()=>document.activeElement.dataset.action),'home');
  await page.keyboard.press('Tab');
  assert.equal(await page.evaluate(()=>document.activeElement.dataset.action),'close-modal');
  await page.keyboard.press('Escape');
  await page.reload();
  state=JSON.parse(await page.evaluate(()=>window.render_game_to_text()));
  assert.equal(state.turn,1);assert.equal(state.drops,1);
  assert.equal(state.mapMode,'realm');
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+1);
  assert.equal(overflow,false,`${label} horizontal overflow`);
  await context.close();
};
try{await run({width:1440,height:900},'desktop');await run({width:1280,height:720},'laptop');await run({width:390,height:844},'mobile');assert.deepEqual(errors,[]);console.log('PASS 3 viewports: full flow, 8 diseases, 6 factions, reading pause/resume, keyboard dialog, disclosure persistence, save reload, no page errors or horizontal overflow');}finally{await browser.close();}
